// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo-dIsggCXPsOZcdFy8ZkPD-pnhwEgxgM',
    appId: '1:1017392932593:android:d15913ab85c9c6def2ab50',
    messagingSenderId: '1017392932593',
    projectId: 'friends-chat-5b40e',
    storageBucket: 'friends-chat-5b40e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAAsnn7CVty79zt4kyIDVOr2oKnxQjaqU',
    appId: '1:1017392932593:ios:4d1ebcfdc37532daf2ab50',
    messagingSenderId: '1017392932593',
    projectId: 'friends-chat-5b40e',
    storageBucket: 'friends-chat-5b40e.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlmgKNN60fZsNgjK0ZDaPnShiBnjG00IA',
    appId: '1:1017392932593:web:3afa6f5c3948b027f2ab50',
    messagingSenderId: '1017392932593',
    projectId: 'friends-chat-5b40e',
    authDomain: 'friends-chat-5b40e.firebaseapp.com',
    storageBucket: 'friends-chat-5b40e.firebasestorage.app',
    measurementId: 'G-RTEPRBMK4G',
  );
}
